models:
  LogisticRegression:
    C:
      - 0.1
      - 1
      - 10
    solver:
      - lbfgs
      - liblinear
    max_iter:
      - 100
      - 200
      - 300

  DecisionTreeClassifier:
    max_depth:
      - 10
      - 20
      - 30
    min_samples_split:
      - 2
      - 5
      - 10
    min_samples_leaf:
      - 1
      - 2
      - 4

  RandomForestClassifier:
    n_estimators:
      - 50
      - 100
      - 200
    max_depth:
      - 30
      - 10
      - 20
    min_samples_split:
      - 2
      - 5

  ExtraTreesClassifier:
    n_estimators:
      - 50
      - 100
      - 200
    max_depth:
      - 30
      - 10
      - 20
    min_samples_split:
      - 2
      - 5
    min_samples_leaf:
      - 1
      - 2

  GradientBoostingClassifier:
    learning_rate:
      - 0.1
      - 0.01
      - 0.5
    n_estimators:
      - 50
      - 100
      - 200
    max_depth:
      - 3
      - 5
      - 7

  AdaBoostClassifier:
    n_estimators:
      - 50
      - 100
      - 200
    learning_rate:
      - 0.01
      - 0.1
      - 1.0

  XGBClassifier:
    n_estimators:
      - 50
      - 100
      - 200
    max_depth:
      - 3
      - 5
      - 7
    learning_rate:
      - 0.1
      - 0.01
      - 0.2

  LGBMClassifier:
    n_estimators:
      - 50
      - 100
      - 200
    max_depth:
      - 3
      - 5
      - 7
    learning_rate:
      - 0.01
      - 0.1
      - 0.2

  CatBoostClassifier:
    iterations:
      - 50
      - 100
      - 200
    depth:
      - 3
      - 5
      - 7
    learning_rate:
      - 0.01
      - 0.1
      - 0.2
